# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 617e710939cc2f6738ffa23e9a32f09a335e5cb45b8a09b46d59782b71e12ee095493d37ae09f8c6fadd3558da83b6ef5c6793833f0cc6684833d6870e6f7c4e

test:
  secret_key_base: f9410aa8526c40228082a975202f5f9947b2e6d1334284fb7b139743bfa206d968cd9f0b93f4f1b7924cdb7e3a26a87c94cfa166620aa060115cc2098f57a92e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
